name: PR Checks

on:
  pull_request:
    branches:
      - main
      - master
      - develop

jobs:
  lint-and-typecheck:
    name: Lint and Type Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run TypeScript type checking
        run: yarn tsc --noEmit

      - name: Run Prettier check
        run: yarn prettier --check 'src/{*,**/*}.{ts,tsx,js,jsx,json}'

      - name: Run ESLint
        run: yarn eslint .

      - name: Run Next.js lint
        run: yarn next lint
